apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agents
  template:
    metadata:
      labels:
        app: agents
    spec:
      containers:
      - name: agent-container
        image: agents:1.0
        ports:
          - name: agentport
            containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: default
spec:
  selector:
    app: agents
  ports:
  - port: 8080
    targetPort: agentport
