apiVersion: apps/v1
kind: Deployment
metadata:
  name: pub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pub
  template:
    metadata:
      labels:
        app: pub
    spec:
      hostNetwork: true
      containers:
      - name: pub-container
        image: pub:1.0
        tty: true
        stdin: true
---
apiVersion: v1
kind: Service
metadata:
  name: pubsub-service
spec:
  type: LoadBalancer
  selector:
    app: echo
  ports:
  - port: 5555
    name: echoport
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      hostNetwork: true
      containers:
      - name: echo-container
        image: echo:1.0
        tty: true
        stdin: true
        ports:
          - name: echoport
            containerPort: 5555
