apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server-container
        image: server:2.1
        tty: true
        stdin: true
        ports:
          - name: serverport
            containerPort: 12300
          - name: monitorport
            containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  selector:
    app: server
  ports:
  - port: 12300
    nodePort: 31234
    name: serverport
  - port: 8000
    nodePort: 31235
    name: monitorport
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agents
  template:
    metadata:
      labels:
        app: agents
    spec:
      containers:
      - name: agents-container
        image: agents:1.0
        tty: true
        stdin: true
