apiVersion: apps/v1
kind: Deployment
metadata:
  name: pub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pub
  template:
    metadata:
      labels:
        app: pub
    spec:
      containers:
      - name: pub-container
        image: pub_monitor:1.0
        tty: true
        stdin: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo-container
        image: echo_monitor:1.0
        tty: true
        stdin: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor-container
        image: monitor:1.0
        tty: true
        stdin: true
        ports:
          -  name: monitorport
             containerPort: 12345
---
apiVersion: v1
kind: Service
metadata:
  name: monitor-service
spec:
  type: NodePort
  selector:
    app: monitor
  ports:
  - port: 12345
    targetPort: 12345
    nodePort: 31234  
