apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-robot-ai-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-robot-ai-2
  template:
    metadata:
      labels:
        app: service-robot-ai-2
    spec:
      containers:
      - name: service-robot-ai-2
        image: service-robot-ai:1.0
        tty: true
        stdin: true
        env:
        - name: ROBOT
          value: leonardo
        - name: DISPLAY
          value: localhost:1.0
      - name: xvfb
        image: comiq/xvfb:latest
        env:
         - name: DISPLAY
           value: "1"
         - name: SCREEN
           value: "0"
        ports:
          - name: xserver
            containerPort: 6001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-robot-ai-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-robot-ai-1
  template:
    metadata:
      labels:
        app: service-robot-ai-1
    spec:
      containers:
      - name: service-robot-ai-1
        image: service-robot-ai:1.0
        tty: true
        stdin: true
        env:
        - name: ROBOT
          value: donatello
        - name: DISPLAY
          value: "localhost:1.0"
      - name: xvfb
        image: comiq/xvfb:latest
        env:
         - name: DISPLAY
           value: "1"
         - name: SCREEN
           value: "0"
        ports:
          - name: xserver
            containerPort: 6001
