apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxylistenerexample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxylistenerexample
  template:
    metadata:
      labels:
        app: proxylistenerexample
    spec:
      containers:
      - name: proxylistenerexample-container
        image: proxylistenerexample:1.0
        tty: true
        stdin: true
        ports:
          -  name: proxylistenerexampleport
             containerPort: 12345
