apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy-container
        image: proxy:1.0
        tty: true
        stdin: true
        ports:
          -  name: proxyport
             containerPort: 12345
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  type: NodePort
  selector:
    app: proxy
  ports:
  - port: 12345
    targetPort: 12345
    nodePort: 31234  
